--------------------------------------------------------
-- DDL for sample database
-- INFO -- ERD ==> DDTT_BOOK
-- INFO -- ERD ==> DDTT_CLASS
-- INFO -- ERD ==> 	|-DDTT_STUDENT_CLASS
-- INFO -- ERD ==> DDTT_SCHOOL
-- INFO -- ERD ==> 	|-DDTT_STUDENT
-- INFO -- ERD ==> 		|-DDTT_STUDENT_CLASS
--------------------------------------------------------

  CREATE TABLE "DDTT_BOOK" 
   (	"ID" NUMBER, 
	"BOOK_NAME" VARCHAR2(20)
   ) ;

  CREATE TABLE "DDTT_CLASS" 
   (	"ID" NUMBER, 
	"CLASS_NAME" VARCHAR2(20)
   ) ;

  CREATE TABLE "DDTT_SCHOOL" 
   (	"ID" NUMBER, 
	"SCHOOL_NAME" VARCHAR2(20)
   ) ;

  CREATE TABLE "DDTT_STUDENT" 
   (	"ID" NUMBER(18,0), 
	"NAME" VARCHAR2(100), 
	"DOB" DATE, 
	"CREATED_TM" TIMESTAMP (6), 
	"SCHOOL_ID" NUMBER
   ) ;

  CREATE TABLE "DDTT_STUDENT_CLASS" 
   (	"CLASS_ID" NUMBER, 
	"STUDENT_ID" NUMBER
   ) ;
  ALTER TABLE "DDTT_BOOK" ADD CONSTRAINT "DDTT_BOOK_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DDTT_BOOK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DDTT_CLASS" ADD CONSTRAINT "DDTT_CLASS_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DDTT_CLASS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DDTT_SCHOOL" ADD CONSTRAINT "DDTT_SCHOOL_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DDTT_SCHOOL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DDTT_STUDENT" ADD CONSTRAINT "DDTT_STUDENT_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "DDTT_STUDENT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DDTT_STUDENT_CLASS" ADD CONSTRAINT "DDTT_STUDENT_CLASS_PK" PRIMARY KEY ("CLASS_ID", "STUDENT_ID") ENABLE;
  ALTER TABLE "DDTT_STUDENT_CLASS" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "DDTT_STUDENT_CLASS" MODIFY ("STUDENT_ID" NOT NULL ENABLE);

  ALTER TABLE "DDTT_STUDENT" ADD CONSTRAINT "DDTT_STUDENT_DDTT_SCHOOL_FK1" FOREIGN KEY ("SCHOOL_ID")
	  REFERENCES "DDTT_SCHOOL" ("ID") ENABLE;

  ALTER TABLE "DDTT_STUDENT_CLASS" ADD CONSTRAINT "DDTT_STUDENT_CLASS_DDTT_CL_FK1" FOREIGN KEY ("CLASS_ID")
	  REFERENCES "DDTT_CLASS" ("ID") ENABLE;
 
  ALTER TABLE "DDTT_STUDENT_CLASS" ADD CONSTRAINT "DDTT_STUDENT_CLASS_DDTT_ST_FK1" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "DDTT_STUDENT" ("ID") ENABLE;
